<?php
$_productCollection = $block->getFitmentParts();
//$_helper = $this->helper('catalog/output');
//$filters = $this->getFitmentFilters();
//$_collectionSize = $_productCollection->count();

echo "testing here ...12345";

foreach ($_productCollection as $product) {
//    print_r($product->getData());
//    echo "<br>";
}
$_collectionSize = $_productCollection->count();

echo $_collectionSize;

die;
?>

<?php if ($_collectionSize && $tmpHtml = $this->getChildHtml('block_category_above_collection')): ?>
    <div class="block_category_above_collection std"><?php echo $tmpHtml; ?></div>
<?php endif; ?>

<?php if (!$_collectionSize): ?>
    <?php if ($tmpHtml = $this->getChildHtml('block_category_above_empty_collection')): ?>
        <div class="block_category_above_empty_collection std"><?php echo $tmpHtml; ?></div>
    <?php else: ?>
        <p class="note-msg empty-catalog"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php endif; ?>
<?php else: ?>

    <?php
    $_helper = $this->helper('catalog/output');
    $theme = $this->helper('ultimo');
    $helpLabels = $this->helper('ultimo/labels');
    $helpTemplate = $this->helper('ultimo/template');
    $helpImg = $this->helper('infortis/image');

    //Image size
    $imgWidth = intval($theme->getCfg('category/image_width'));
    $imgHeight = $imgWidth;

    //If image width is not specified, use default values
    if ($imgWidth <= 0) {
        $imgWidth = 295;
        $imgHeight = 295;
    }

    //Image aspect ratio settings
    $keepAspectRatio = $theme->getCfg('category/aspect_ratio');
    if ($keepAspectRatio) {
        $imgHeight = 0; //Height will be calculated automatically (based on width) to keep the aspect ratio
        $catViewKeepFrame = FALSE;
    } else {
        $catViewKeepFrame = TRUE;
    }

    if (Mage::registry('catViewKeepFrame') === NULL) {
        Mage::register('catViewKeepFrame', $catViewKeepFrame);
    }

    //Hide toolbar
    $hideToolbar = false;
    if ($this->getHideToolbar()) {
        $hideToolbar = true;
    }
    ?>

    <div class="productWrapper">
        <span id='ajax_loader' style='display:none; z-index: 999'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>'/></span>


    <?php
    //Get grid configuration array
    $gc = $theme->getCfgGroup('category_grid');

    //Get number of columns (from parameter or from theme config)
    $columnCount = 3;
    if ($this->getGridColumnCount()) {
        $columnCount = $this->getGridColumnCount();
    } else {
        $columnCount = $gc['column_count'];
    }

    //Grid classes
    $gridClasses = '';
    $productNameClasses = '';
    if ($gc['display_name'] == 2 && $gc['display_name_single_line'] == true)
        $gridClasses .= ' single-line-name';
    if ($gc['display_name'] == 1)
        $productNameClasses .= ' display-onhover';
    if ($gc['centered'])
        $gridClasses .= ' centered';
    if ($gc['hover_effect'])
        $gridClasses .= ' hover-effect';
    if ($gc['equal_height'])
        $gridClasses .= ' equal-height';

    //Size of grid elements
    if ($gc['elements_size']) {
        $gridClasses .= ' size-' . $gc['elements_size'];
    } else {
        //Calculate size based on number of columns
        if ($columnCount >= 6) {
            $gridClasses .= ' size-xs';
        } elseif ($columnCount >= 4) {
            $gridClasses .= ' size-s';
        }
    }

    //Container "actions" at the bottom of the grid item stores button and add-to links
    //If at least one of those elements was set as "Display on hover" but no element was set as "Display":
    //apply appropriate classes to the container.
    $actionsClasses = '';
    if ($gc['display_addtocart'] == 1 || ($gc['display_addtolinks'] == 1 && !$gc['addtolinks_simple'])) {
        $actionsClasses = ' display-onhover';
    }
    if ($gc['display_addtocart'] == 2 || ($gc['display_addtolinks'] == 2 && !$gc['addtolinks_simple'])) {
        $actionsClasses = '';
    }
    ?>

        <?php foreach ($_productCollection as $_product): ?>
            <div class="proInfoCol product-blocks">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>">
                    <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                </a>
                <div class="sku">
                    <p>Part # <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'name') ?></p>
                </div>
                <div class="productInfo">
        <?php if ($gc['display_name'] != 0): ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo (strlen(strip_tags($this->stripTags($_product->getName(), null, true))) > 50 ? substr(strip_tags($this->stripTags($_product->getName(), null, true)), 0, 50) . '..' : strip_tags($this->stripTags($_product->getName(), null, true))); ?></a>
                    <?php endif; ?>
                    <ul>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/blank-star.jpg'); ?>" alt="No Star" />
                        </li>
                        <li>
        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>">
                                    <img src="<?php echo $this->getSkinUrl('images/fev.png'); ?>" alt="add to wishlist" />
                                </a>
        <?php endif; ?>
                            <?php /* if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                              <a href="<?php echo $_compareUrl ?>"><img src="<?php echo $this->getSkinUrl('images/compare.png'); ?>" alt="quick compare" /></a>
                              <?php endif; */ ?> 
                        </li>   
                    </ul>

                    <ul>
                        <li><p><?php echo $this->getPriceHtml($_product, true); ?></p></li>
        <?php if ($gc['display_addtocart'] != 0): //Cart button   ?>
                            <?php if (!$_product->canConfigure() && $_product->isSaleable()): ?>
                                <li>
                                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                <?php /* <span id='ajax_loader' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span> */ ?>
                                </li>
                                <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
    <?php endforeach; ?>            

        <?php if (!$hideToolbar): ?>
            <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
            </div>
            <?php endif; ?>
    </div>
    <?php endif; ?>

<?php if ($_collectionSize && $tmpHtml = $this->getChildHtml('block_category_below_collection')): ?>
    <div class="block_category_below_collection std"><?php echo $tmpHtml; ?></div>
<?php endif; ?>