<?php
/** @var \Zemez\Blog\Block\Widget\PostList $block */
$dateFormat = $this->getDateFormat();
if ($block->isEnabledCarousel()) {
    $itemWidth = "";
} else {
    $itemWidth = $block->getPostAmountPerRow() ? sprintf('flex-basis: %1$.2f%%; -webkit-flex-basis: %1$.2f%%; max-width: %1$.2f%%;', 100 / $block->getPostAmountPerRow()) : '';
}
?>
<?php $id_my_widget = rand(1,100); ?>
<?php if(!$block->isEnabledCarousel()): ?>
<style>
    @media (min-width: 991px) {
        .id-<?php echo $id_my_widget; ?> .post-items > .post-item {
            <?php echo $itemWidth ?>
        }
    }
</style>
 <?php endif;  ?>

<?php if ($posts = $this->getPosts()) : ?>
    <div class="widget blog-posts widget-post-grid bg-light id-<?php echo $id_my_widget; ?>">
        <div class="container">
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php echo __($block->getTitle()) ?></strong>
            </div>
            <div class="block-content">
                <div class="posts-grid post-items<?php if ($block->isEnabledCarousel()): ?> owl-carousel<?php endif; ?>"<?php if ($block->isEnabledCarousel()): ?> data-mage-init='{"blogCarousel": { "responsive": { "1200": { "items" : "<?php /* @escapeNotVerified */ echo $block->getPostAmountPerView(); ?>" }}}}'<?php endif; ?>>
                    <?php foreach ($posts as $post): ?>
                        <div class="post-item">
                            <div class="item-wrapper">
                                <!-- Image -->
                                <?php if ($image = $post->getImage()): ?>
                                    <div class="post-image">
                                        <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $image ?>"  alt=""/></a>
                                    </div>
                                <?php endif; ?>

                                <!-- Metadata -->
                                <div class="post-data">
                                    <time class="create-date"><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                                </div>

                                <!-- Title -->
                                <h6 class="post-title">
                                    <a href="<?php echo $this->getPostUrl($post); ?>">
                                        <?php echo $block->getStringTruncated($post->getTitle(), $block->getPostTitleLength()) ?>
                                    </a>
                                </h6>

                                <!-- Short Description -->
                                <div class="post-short-content">
                                    <?php echo $block->filterContent($block->getStringTruncated($post->getShortContent(), $block->getPostDescLength())); ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>