<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="pager">
        <?php endif ?>

        <?php if ($block->getShowAmounts()) : ?>
            <p class="toolbar-amount">
                <span class="toolbar-number">
                    <?php if ($block->getLastPageNum() > 1) : ?>
                        <?= $block->escapeHtml(__('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum())) ?>
                    <?php elseif ($block->getTotalNum() == 1) : ?>
                        <?= $block->escapeHtml(__('%1 Item', $block->getTotalNum())) ?>
                    <?php else : ?>
                        <?= $block->escapeHtml(__('%1 Item(s)', $block->getTotalNum())) ?>
                    <?php endif; ?>
                </span>
            </p>
        <?php endif ?>

        <?php if ($block->getShowPerPage()): ?>
            <div class="limiter">
                <label><?php echo __('Show') ?></label>
                <select onchange="setLocation(this.value)">
                    <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                        <option value="<?php echo $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                </select><span class="per-page"> <?php echo __('per page') ?></span>
            </div>
        <?php endif ?>

        <?php if ($block->getLastPageNum() > 1): ?>
            <div class="pages">
                <strong><?php echo __('Page:') ?></strong>
                <ul class="items pages-items" aria-labelledby="paging-label">
                    <?php if (!$block->isFirstPage()): ?>                        
                        <li class="item pages-item-previous">
                            <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $block->getCollection()->getCurPage(-1); ?>
                            <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : ''; ?>
                            <a class="<?= $block->escapeHtmlAttr($text ? 'link ' : 'action ') ?> previous"
                               href="javascript:void(0)"
                               data-pageurl="<?php echo $pageUrl ?>"
                               title="<?= $block->escapeHtmlAttr($text ? $text : __('Previous')) ?>">
                                <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                                <span><?= $block->escapeHtml($text ? $text : __('Previous')) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>

                    <?php if ($block->canShowFirst()): ?>
                        <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=1'; ?>
                        <li class="item"><a class="page first" href="javascript:void(0)" data-pageurl="<?php echo $pageUrl ?>">1</a></li>
                    <?php endif; ?>

                    <?php if ($block->canShowPreviousJump()): ?>
                        <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $block->getPreviousJumpPage(); ?>
                        <li class="item"><a class="previous_jump" href="javascript:void(0)" data-pageurl="<?php echo $pageUrl ?>">...</a></li>
                    <?php endif; ?>

                    <?php foreach ($block->getFramePages() as $_page): ?>
                        <?php if ($block->isPageCurrent($_page)): ?>
                            <li class="item current">
                                <strong class="page">
                                    <span class="label"><?= $block->escapeHtml(__('You\'re currently reading page')) ?></span>
                                    <span><?= $block->escapeHtml($_page) ?></span>
                                </strong>
                            </li>
                        <?php else: ?>
                            <li class="item">
                                <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $_page; ?>
                                <a href="javascript:void(0)" class="page" data-pageurl="<?php echo $pageUrl ?>"><?php echo $_page ?></a>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>

                    <?php if ($block->canShowNextJump()): ?>
                        <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $block->getNextJumpPage(); ?>
                        <li class="item"><a class="page next_jump" href="javascript:void(0)"  data-pageurl="<?php echo $pageUrl ?>">...</a></li>
                    <?php endif; ?>

                    <?php if ($block->canShowLast()): ?>
                        <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $block->getLastPageNum(); ?>
                        <li class="item"><a class="page last" href="javascript:void(0)" data-pageurl="<?php echo $pageUrl ?>"><?php echo $block->getLastPageNum() ?></a></li>
                    <?php endif; ?>

                    <?php if (!$block->isLastPage()): ?>
                        <li class="item next">
                            <?php $pageUrl = $block->getUrl('vehicle/search/all/') . '?p=' . $block->getCollection()->getCurPage(+1); ?>
                            <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : ''; ?>
                            <a class="<?= /* @noEscape */ $text ? 'link ' : 'action ' ?> next"
                               href="javascript:void(0)"
                               title="<?= $block->escapeHtmlAttr($text ? $text : __('Next')) ?>" 
                               data-pageurl="<?php echo $pageUrl ?>">
                                <span class="label"><?= $block->escapeHtml(__('Page')) ?></span>
                                <span><?= $block->escapeHtml($text ? $text : __('Next')) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if ($block->isShowPerPage()) : ?>
            <div class="limiter">
                <strong class="limiter-label"><?= $block->escapeHtml(__('Show')) ?></strong>
                <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                    <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
                        <option value="<?= $block->escapeHtmlAttr($block->getLimitUrl($_key)) ?>"
                        <?php if ($block->isLimitCurrent($_key)) : ?>
                                    selected="selected"<?php endif ?>>
                                    <?= $block->escapeHtml($_limit) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <span class="limiter-text"><?= $block->escapeHtml(__('per page')) ?></span>
            </div>
        <?php endif ?>

        <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif
?>

<script type="text/javascript">
    requirejs(['jquery'], function ($) {
        'use strict';

        var pager = (function ($) {
            return {
                init: function () {
                    console.log("pager init");
                },
                loadPageContent: function (url) {
                    $.ajax({
                        showLoader: true,
                        type: 'get',
                        url: url,
                        dataType: 'html',
                        data: {
                            pid: '<?php echo $block->getData("productid") ?>'
                        },
                        beforeSend: function () {
                            console.log(url);
                        },
                        success: function (data) {
                            $('.product-vehicle-container').html(data);

                            $(".item .page").on("click", function () {
                                var pageurl = $(this).data("pageurl");
                                pager.loadPageContent(pageurl);
                            });
                        },
                        error: function (data, error, status) {
                            console.log('An error occurred.');
                            console.log(status);
                        }
                    });
                }
            };
        })($);


        $(".item .page").on("click", function () {
            var pageurl = $(this).data("pageurl");
            pager.loadPageContent(pageurl);
        });

        pager.init();

    });
</script>