<?php

$makes = $block->getMakes();
$options = ['' => 'Make'];

if (is_array($makes)) {
    foreach ($makes as $key => $value) {
        $options[$value->MakeID] = $value->MakeName;
    }
} else {
    $options[$makes->MakeID] = $makes->MakeName;
}

$title = "";
$res = "";

foreach ($options as $key => $value) {
    $res .= sprintf('<option value="%s" data-title="' . $title . '">%s</option>', htmlspecialchars($key), htmlspecialchars($value));
}

echo $res;