<?php

$models = $block->getModels();
$options = ['' => 'Model'];

if (is_array($models)) {
    foreach ($models as $key => $value) {
        $options[$value->ModelID] = $value->ModelName;
    }
} else {
    $options[$models->ModelID] = $models->ModelName;
}

$title = "";
$res = "";

foreach ($options as $key => $value) {
    $res .= sprintf('<option value="%s" data-title="' . $title . '">%s</option>', htmlspecialchars($key), htmlspecialchars($value));
}

echo $res;