<?php

$submodels = $block->getSubmodels();
$options = ['' => 'SubModel'];

if (is_array($submodels)) {
    foreach ($submodels as $key => $value) {
        $options[$value->SubModelID] = $value->SubModelName;
    }
} else {
    $options[$submodels->SubModelID] = $submodels->SubModelName;
}

$title = "";
$res = "";

foreach ($options as $key => $value) {
    $res .= sprintf('<option value="%s" data-title="' . $title . '">%s</option>', htmlspecialchars($key), htmlspecialchars($value));
}

echo $res;