<?php
$fitment_models = $fitment_models_mobile = $block->getFitmentModels();
$models = $fitment_models;
?>
<?php foreach ($models as $key => $model): ?>
    <?php array_shift($fitment_models); ?>
    <?php $model_image = $block->getModelImage(intval($model->ModelID)); ?>
    <div class="fitment-selection">
        <div class="product-item-info">
            <div class="product-img">                
                <a href="#" class="fitment-slider-model fitment-slider-item" data-url="<?php echo $block->getUrl("fitment/slider/submodels"); ?>" data-year="<?php echo $block->year; ?>" data-makeid="<?php echo $block->make; ?>" data-modelid="<?php echo $model->ModelID; ?>">
                    <img class="fitment-model-img-thumb img-fluid" src="<?php echo $model_image; ?>" alt="<?php echo $model->ModelName; ?>" />                                                
                </a>
            </div>
            <div class="fitment-selection-title text-uppercase text-center">
                <a href="#" class="fitment-slider-model fitment-slider-item" data-url="<?php echo $block->getUrl("fitment/slider/submodels"); ?>" data-year="<?php echo $block->year; ?>" data-makeid="<?php echo $block->make; ?>" data-modelid="<?php echo $model->ModelID; ?>"><?php echo $model->ModelName; ?></a>
                <i class="fa fa-caret-right"></i>
            </div>
        </div>
    </div>
    <?php
endforeach;
