<?php /**   */ ?>
<?php
$optionsHelper = $this->helper('Zemez\ThemeOptions\Helper\Data');
?>

<?php if($optionsHelper->getLogoType() == 'text'): ?>
    /** Logo **/
    <?php
    $logoFontSize = $optionsHelper->getLogoFontSize();
    $logoLineHeight = $optionsHelper->getLogoLineHeight();
    $logoTextColor = $optionsHelper->getLogoTextColor();
    ?>
    .logo-text {
        <?= $logoFontSize ? 'font-size: ' . $logoFontSize . 'px;' : '' ?>
        <?= $logoLineHeight ? 'line-height: ' . $logoLineHeight . 'px;' : '' ?>
        <?= $logoTextColor ? 'color: ' . $logoTextColor . ';' : '' ?>
    }
    <?php if($optionsHelper->isSlogan()): ?>
        <?php
        $sloganPosition = $optionsHelper->getSloganPosition();
        $direction = 'row';
        if ($sloganPosition == 'top') {
            $direction = 'column-reverse';
        } elseif($sloganPosition == 'bottom') {
            $direction = 'column';
        } elseif($sloganPosition == 'left') {
            $direction = 'row-reverse';
        }
        $sloganFontSize = $optionsHelper->getSloganFontSize();
        $sloganLineHeight = $optionsHelper->getSloganLineHeight();
        $sloganTextColor = $optionsHelper->getSloganTextColor();
        ?>
        .logo {
            display:flex;
            flex-direction: <?= $direction; ?>;
        }
        .logo .slogan {
            <?= $sloganFontSize ? 'font-size: ' . $sloganFontSize . 'px;' : '' ?>
            <?= $sloganLineHeight ? 'line-height: ' . $sloganLineHeight . 'px;' : '' ?>
            <?= $sloganTextColor ? 'color: ' . $sloganTextColor . ';' : '' ?>
        }
    <?php endif; ?>
    /** end Logo **/
<?php elseif($optionsHelper->getLogoType() == 'image'): ?>
    /** Logo **/
    <?php if($optionsHelper->isImageSlogan()): ?>
        <?php
        $imageSloganPosition = $optionsHelper->getImageSloganPosition();
        $direction = 'row';
        if ($imageSloganPosition == 'top') {
            $direction = 'column-reverse';
        } elseif ($imageSloganPosition == 'bottom') {
            $direction = 'column';
        } elseif ($imageSloganPosition == 'left') {
            $direction = 'row-reverse';
        }
        $imageSloganFontSize = $optionsHelper->getImageSloganFontSize();
        $imageSloganLineHeight = $optionsHelper->getImageSloganLineHeight();
        $imageSloganTextColor = $optionsHelper->getImageSloganTextColor();
        ?>
        .logo {
            display:flex;
            flex-direction: <?= $direction; ?>;
        }
        .logo .slogan {
            <?= $imageSloganFontSize ? 'font-size: ' . $imageSloganFontSize . 'px;' : '' ?>
            <?= $imageSloganLineHeight ? 'line-height: ' . $imageSloganLineHeight . 'px;' : '' ?>
            <?= $imageSloganTextColor ? 'color: ' . $imageSloganTextColor . ';' : '' ?>
        }
    <?php endif; ?>
    /** end Logo **/
<?php endif; ?>

<?php if($optionsHelper->getColorSchemeStatus()): ?>
    /** Primary Color **/
    <?php if ($optionsHelper->getPrimaryColor()): ?>
        /* put this selectors for primary color/background */
        a:hover,
        .alink:hover,
        .message.info a:hover,
        .message.info a:active,
        .message.error a:hover,
        .message.error a:active,
        .message.warning a:hover,
        .message.warning a:active,
        .message.notice a:hover,
        .message.notice a:active,
        .message.success a:hover,
        .message.success a:active,
        .pages a.page:hover,
        .pages strong.page,
        .pages .action:hover,
        .pages .action.next:hover:before,
        .pages .action.previous:hover:before,
        .pages a.link:hover,
        .breadcrumbs a:hover,
        .cart.table-wrapper .action.help.map:hover,
        .opc-wrapper .edit-address-link:hover,
        .opc-block-shipping-information .shipping-information-title .action-edit:hover,
        .action-auth-toggle:hover,
        .checkout-payment-method .checkout-billing-address .action-cancel:hover,
        .checkout-agreements-block .action-show:hover,
        .cart-summary .block.giftcard .action.check:hover,
        .gift-options .actions-toolbar .action-cancel:hover,
        .table-comparison .wishlist.split.button > .action:hover,
        .product-items .wishlist.split.button > .action:hover,
        .paypal-button-widget .paypal-button:hover,
        .cart.table-wrapper .action.help.map:hover,
        .opc-wrapper .edit-address-link:hover,
        .opc-block-shipping-information .shipping-information-title .action-edit:hover,
        .action-auth-toggle:hover,
        .checkout-payment-method .checkout-billing-address .action-cancel:hover,
        .checkout-agreements-block .action-show:hover,
        .cart-summary .block.giftcard .action.check:hover,
        .gift-options .actions-toolbar .action-cancel:hover,
        .table-comparison .wishlist.split.button > .action:hover,
        .product-items .wishlist.split.button > .action:hover,
        .paypal-button-widget .paypal-button:hover,
        button.map-show-info:hover,
        .cart.table-wrapper .actions-toolbar > .action.map-show-info:hover,
        .action-gift.map-show-info:hover,
        button.map-show-info:hover,
        .cart.table-wrapper .actions-toolbar > .action.map-show-info:hover,
        .action-gift.map-show-info:hover,
        .message.global.noscript a:hover,
        .message.global.cookie a:hover,
        .message.global.demo a:hover,
        .my-credit-cards .action.delete:hover,
        .my-credit-cards .action.delete:hover,
        .my-credit-cards-popup .action.secondary:hover,
        .my-credit-cards-popup .action.secondary:hover,
        .product-item .price-box .special-price,
        .modes a.modes-mode:hover,
        .ui-dialog-titlebar-close:hover,
        .ui-dialog-titlebar-close:hover,
        .sidebar .block-wishlist .wishlist-counter span,
        .block-wishlist .wishlist-counter span,
        #search_mini_form .search-autocomplete .search-item .price-box .special-price,
        .catalog-image-grid .category-grid .category-link:hover,
        .catalog-image-grid .category-list .category-link:hover,
        .catalog-image-grid .category-grid .button-more,
        .catalog-image-grid .category-list .button-more,
        .catalog-image-grid .category-grid .subcategory-grid .subcategory-link:hover,
        .catalog-image-grid .category-list .subcategory-grid .subcategory-link:hover,
        .sidebar .block.block-brand .brand-item .brand-item-name a,
        .brand-list .brand-item .brand-item-name a,
        .scrollToTop:hover,
        em,
        .color-primary,
        .sm-header_customer-menu-toggle:hover:before,
        .sm-header_customer-menu-toggle:hover:after,
        .modal-custom .action-close:hover:before,
        .modal-popup .action-close:hover:before,
        .modal-slide .action-close:hover:before,
        .modal-custom .action-close:focus:before,
        .modal-popup .action-close:focus:before,
        .modal-slide .action-close:focus:before,
        .modal-custom .action-close:active:before,
        .modal-popup .action-close:active:before,
        .modal-slide .action-close:active:before,
        .field.choice > input[type=checkbox] + .label:before,
        .field.choice > input[type=radio] + .label:before,
        .product-details .box-tocart .fieldset .special-price,
        .product-wrap .product-info-stock-sku > .product.attribute.sku .value,
        .product-wrap .product-info-price .price-box .special-price,
        .product-wrap .product-brand-name a:hover,
        .catalog-product-view .product.data.items .additional-attributes .attributes-caption,
        .block.related .block-actions .select,
        .block.upsell .block-actions button.action.select,
        .block.upsell .block-actions .cart.table-wrapper .actions-toolbar > .action.action.select,
        .block.upsell .block-actions .action-gift.action.select,
        .minicart-wrapper .action.showcart:hover:before,
        .minicart-wrapper .action.showcart:hover:after,
        .minicart-wrapper .block-minicart .action.close:hover,
        .minicart-wrapper .block-minicart .minicart-items .product-item > .product .product-item-name a:hover,
        .minicart-wrapper .block-minicart .minicart-items .details-qty .update-cart-item,
        .minicart-wrapper .block-minicart .minicart-items .product.options[role="tablist"] .toggle,
        .minicart-wrapper .block-minicart .minicart-items .product.actions a:hover:before,
        #gift-options-cart .gift-options-title,
        #shopping-cart-table .cart.item .product-item-details .product-item-name a:hover,
        .cart-container .cart-summary .checkout.methods .item .action.multicheckout:hover,
        .cart-container .cart-summary .block .title[role="tab"],
        .opc-progress-bar .opc-progress-bar-item,
        #opc-sidebar .items-in-cart > .title span:first-child,
        .table-checkout-shipping-method td:first-child span.radio:before,
        .field.required .control div.field-tooltip.toggle._active .field-tooltip-action:before,
        ._keyfocus .field.required .control div.field-tooltip.toggle .field-tooltip-action:focus:before,
        #checkout-step-payment input[name="billing-address-same-as-shipping"] + label span:before,
        #checkout-step-payment .discount-code .payment-option-title,
        .sidebar .account-navigation li.current strong,
        .sidebar .account-navigation a,
        .block-dashboard-info .box-actions .action.edit:hover,
        .block-dashboard-addresses .box-actions .action.edit:hover,
        .box-billing-address .box-actions .action.edit:hover,
        .box-address-shipping .box-actions .action.edit:hover,
        .block-addresses-list .block-content .action.edit:hover,
        .block-addresses-list .block-content .action.delete:hover,
        .popup-authentication .block-title,
        .account-nav .account-nav-content .item a:hover,
        .account-nav .account-nav-content .item.current,
        .page-product-downloadable .page-main .product-options-wrapper .legend,
        .page-product-grouped .table.grouped .table-caption,
        .filter-current--wrapper .filter-current .item .action.remove:hover,
        .filter-current--wrapper .filter-clear,
        .filter-options .filter-options-content .item a:hover,
        .filter-options .filter-options-content a:hover .count,
        #cart-sidebar-reorder .product-item-link:hover,
        #cart-sidebar-reorder .control .label:before,
        .block-search .label:hover:before,
        .block-search form button.action.search,
        .block-search form .cart.table-wrapper .actions-toolbar > .action.action.search,
        .block-search form .action-gift.action.search,
        .cms-about-us .skills .value,
        .about-us_services .about-us_services_txt i,
        .contact-index-index .contact-us-info .contact-us-info-description:not(.contact-us-info-description-email) a:hover,
        .form.search.advanced legend.legend,
        .sales-guest-form .admin__legend,
        .shipping-delivery-page ul li:before,
        .shipping-delivery-page [class*='themeicon-']:before,
        .faq-page #faq-accordion .accordion-content p:before,
        .support-page .boxes-block li div span:before,
        .guarantee-page h4:before,
        .terms-conditions-page ul h4:before,
        .bg-dark + .top-container + .breadcrumbs a:hover,
        .footer.content .contact-info [href*='tel:']:hover,
        .page-footer .footer-col .footer.links li.current,
        .page-footer .footer-col .footer.links li.current > *,
        .page-footer .footer-col .footer.links li.current strong,
        .timer-wrapper > div span,
        .slider-title a:hover,
        .slider-title a:focus,
        .page-footer.layout-3 a:hover,
        .brand-list .brand-item .brand-item-name a,
        .sidebar .block.block-brand .brand-item .brand-item-name a,
        .sm-wrapper .sm-main #sm-content-block .sm-title,
        .sm-wrapper .sm-main #sm-timer-block .sm-timer-wrapper,
        .customer-account .customer-name,
        .page-header .switcher .options .action.toggle.active,
        .page-header .switcher .options .action.toggle:hover {
          color: <?= $optionsHelper->getPrimaryColor(); ?>;
        }

        mark,
        .bg-primary,
        .opc-progress-bar .opc-progress-bar-item._active > span:before,
        .checkout-container .authentication-wrapper button.action-auth-toggle,
        .checkout-container .authentication-wrapper .cart.table-wrapper .actions-toolbar > .action.action-auth-toggle,
        .checkout-container .authentication-wrapper .action-gift.action-auth-toggle,
        body.account .box a.action:hover,
        .sidebar .price-slider .ui-slider-handle,
        .sidebar .price-slider .ui-slider-range,
        .faq-page #faq-accordion .accordion-trigger:before,
        .support-page .boxes-block li div:hover,
        .page-header__panel {
          background-color: <?= $optionsHelper->getPrimaryColor(); ?>;
        }

        .action.primary:before,
        .block-event .slider-panel .slider .item .action.event:before,
        .product-wrap .product.media .fotorama__thumb-border,
        .cart-container .cart-summary .block.discount button.apply:before,
        .cart-container .cart-summary .block.discount .cart.table-wrapper .actions-toolbar > .action.apply:before,
        .cart-container .cart-summary .block.discount .action-gift.apply:before,
        .swatch-attribute [class*="swatch-opt"] .swatch-option.image:hover,
        [class*="swatch-opt"] .swatch-attribute .swatch-option.image:hover,
        .swatch-attribute [class*="swatch-opt"] .swatch-option.image.selected,
        [class*="swatch-opt"] .swatch-attribute .swatch-option.image.selected,
        .swatch-attribute [class*="swatch-opt"] .swatch-option.image:not(.disabled):hover,
        [class*="swatch-opt"] .swatch-attribute .swatch-option.image:not(.disabled):hover,
        .support-page .boxes-block li div,
        .sm-wrapper .sm-main #sm-subscription-block .sm-content .sm-button:before {
          border-color: <?= $optionsHelper->getPrimaryColor(); ?>;
        }

        .action.primary,
        .scrollToTop,
        .block-event .slider-panel .slider .item .action.event,
        .cart-container .cart-summary .block.discount button.apply,
        .cart-container .cart-summary .block.discount .cart.table-wrapper .actions-toolbar > .action.apply,
        .cart-container .cart-summary .block.discount .action-gift.apply,
        .sm-wrapper .sm-main #sm-subscription-block .sm-content .sm-button {
          background-color: <?= $optionsHelper->getPrimaryColor(); ?>;
          border-color: <?= $optionsHelper->getPrimaryColor(); ?>;
        }

        .product-wrap .product.media .fotorama__arr:hover:before {
          border-color: <?= $optionsHelper->getPrimaryColor(); ?>;
          color: <?= $optionsHelper->getPrimaryColor(); ?>;
        }

        @media all and (min-width: 640px) {
          .column .block-addbysku .action.remove:hover,
          .column .block-addbysku .action.remove:hover {
            color: <?= $optionsHelper->getPrimaryColor(); ?>;
          }
        }

        @media (max-width: 767px) {
          .link.wishlist a:hover,
          .navigation .level0 > .level-top:hover,
          .navigation .submenu > li > a:hover,
          .navigation .submenu:not(:first-child) ul > li a:hover,
          .sm-header_customer-menu-container .sm-header_customer-menu .welcome,
          div.sm-header_customer-menu-container .mage-dropdown-dialog .switcher .switcher-options .switcher-trigger:hover,
          div.sm-header_customer-menu-container .mage-dropdown-dialog .switcher .mage-dropdown-dialog a:hover,
          .link.compare a:hover,
          .opc-estimated-wrapper .estimated-price,
          .block-search .label.active:hover:after {
            color: <?= $optionsHelper->getPrimaryColor(); ?>;
          }
        }

        @media (min-width: 1750px) {
          .page-header.layout-3 .minicart-wrapper .action.showcart .counter.qty .counter-number,
          .page-header.layout-3 .link.wishlist .counter.qty,
          .page-header.layout-3 .link.compare .counter.qty,
          .page-header.layout-3 .block-search form.minisearch .label:hover {
            color: <?= $optionsHelper->getPrimaryColor(); ?>;
          }
        }
    <?php endif; ?>
    /**/

    /** Secondary Color **/
    <?php if ($optionsHelper->getSecondaryColor()): ?>
        /* put this selectors for secondary color/background */
        .search-autocomplete,
        .product-items .action.towishlist:hover,
        .products.list.items .action.towishlist:hover,
        .table-comparison .action.towishlist:hover,
        .product-addto-links .action.towishlist:hover,
        .action.secondary:hover,
        .action.secondary-2,
        .product-items .action.tocompare:hover,
        .products.list.items .action.tocompare:hover,
        .table-comparison .action.tocompare:hover,
        .product-addto-links .action.tocompare:hover,
        .block-search form button.action.search:hover,
        .block-search form .cart.table-wrapper .actions-toolbar > .action.action.search:hover,
        .block-search form .action-gift.action.search:hover,
        .footer.content a:hover,
        .footer.content .contact-info [href*='tel:'],
        nav.tm-navigation .megamenu-wrapper ul.mm-submenu a:hover,
        nav.tm-navigation .megamenu-wrapper ul.mm-submenu a.ui-state-focus:hover,
        nav.tm-navigation .megamenu-wrapper ul.mm-submenu a.ui-state-active:hover {
          color: <?= $optionsHelper->getSecondaryColor(); ?>;
        }

        .link.wishlist .counter.qty,
        .action.secondary,
        .action.secondary-2:hover,
        .link.compare .counter.qty,
        .minicart-wrapper .action.showcart .counter.qty {
          background-color: <?= $optionsHelper->getSecondaryColor(); ?>;
        }

        .action.secondary,
        .action.secondary-2,
        .stuckElement:after {
          border-color: <?= $optionsHelper->getSecondaryColor(); ?>;
        }

        @media only screen and (max-width: 767px) {
          .navigation .level0.active .all-category .ui-state-focus,
          .navigation .level0.active > a:not(.ui-state-active),
          .navigation .level0.has-active > a:not(.ui-state-active) {
            border-color: <?= $optionsHelper->getSecondaryColor(); ?>;
          }
        }

        @media all and (min-width: 768px), print {
          .navigation .level0 .submenu a:hover,
          .navigation .level0 .submenu a.ui-state-focus,
          .navigation .level0 .submenu .active > a,
          .navigation .level0 .submenu a.ui-state-active {
            background-color: <?= $optionsHelper->getSecondaryColor(); ?>;
          }
          .navigation .level0 > .level-top:before {
            border-color: <?= $optionsHelper->getSecondaryColor(); ?>;
          }
        }
    <?php endif; ?>
    /**/

    <?php if ($optionsHelper->getBodyBackgroundColor()): ?>
        body {
            background-color: <?= $optionsHelper->getBodyBackgroundColor(); ?>;
        }
    <?php endif; ?>
    <?php if ($optionsHelper->isBodyBackgroundImage()) : ?>
        body {
            background-image: <?= $optionsHelper->getBodyBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getBodyBackgroundImage() . ')' : 'none' ?>;
            background-size: <?= $optionsHelper->getBodyBackgroundImageSize(); ?>;
            background-attachment: <?= $optionsHelper->getBodyBackgroundImageAttachment(); ?>;
            background-position: <?= $optionsHelper->getBodyBackgroundImagePosition(); ?>;
            background-repeat: <?= $optionsHelper->getBodyBackgroundImageRepeat(); ?>;
        }
    <?php endif; ?>

    <?php if ($optionsHelper->getHeaderBackgroundColor()): ?>
        header.page-header {
            background-color: <?= $optionsHelper->getHeaderBackgroundColor(); ?>;
        }
    <?php endif; ?>

    <?php if ($optionsHelper->isHeaderBackgroundImage()) : ?>
        header.page-header {
            background-image: <?= $optionsHelper->getHeaderBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getHeaderBackgroundImage() . ')' : 'none' ?>;
            background-size: <?= $optionsHelper->getHeaderBackgroundImageSize(); ?>;
            background-attachment: <?= $optionsHelper->getHeaderBackgroundImageAttachment(); ?>;
            background-position: <?= $optionsHelper->getHeaderBackgroundImagePosition(); ?>;
            background-repeat: <?= $optionsHelper->getHeaderBackgroundImageRepeat(); ?>;
        }
    <?php endif; ?>


    <?php if ($optionsHelper->getFooterBackgroundColor()): ?>
        .page-footer {
            background-color: <?= $optionsHelper->getFooterBackgroundColor(); ?>;
        }
    <?php endif; ?>

    <?php if ($optionsHelper->isFooterBackgroundImage()) : ?>
        .page-footer {
            background-image: <?= $optionsHelper->getFooterBackgroundImage() ? 'url(' . $this->getBaseUrl() . 'pub/media/theme_options/' . $optionsHelper->getFooterBackgroundImage() . ')' : 'none' ?>;
            background-size: <?= $optionsHelper->getFooterBackgroundImageSize(); ?>;
            background-attachment: <?= $optionsHelper->getFooterBackgroundImageAttachment(); ?>;
            background-position: <?= $optionsHelper->getFooterBackgroundImagePosition(); ?>;
            background-repeat: <?= $optionsHelper->getFooterBackgroundImageRepeat(); ?>;
        }
    <?php endif; ?>

    <?php if ($optionsHelper->getPrimaryFontColor()): ?>
        body {
            color: <?= $optionsHelper->getPrimaryFontColor(); ?>;
        }
    <?php endif; ?>

    <?php if ($optionsHelper->getPrimaryLinkColor()): ?>
        a {
            color: <?= $optionsHelper->getPrimaryLinkColor(); ?>;
        }
    <?php endif; ?>
<?php endif; ?>

/* Category page */
<?php if ($columns = $optionsHelper->getProductItemWidth()): ?>
    @media screen and (min-width: 1024px) {
        .grid-main .products-grid .product-item{
            flex-basis: <?= $columns; ?>;
            max-width: <?= $columns; ?>;
        }
    }
<?php endif; ?>
<?php if ($optionsHelper->isTiltJs()): ?>
    .js-tilt-glare {
        pointer-events: none;
    }
<?php endif ?>
/* END Category page */
