<?php /** @var \Zemez\ThemeOptions\Block\SocialLinks $block */ ?>

<?php if($block->getAlign()): ?>
    <style>
        @media (min-width: 768px) {
            ul.social-links.position-<?php echo $block->getPosition() ?> {
                text-align: <?php echo $block->getAlign() ?: 'left'; ?>;
            }
        }
    </style>
<?php endif; ?>

<h4 class="social-links-title"><?= /* @escapeNotVerified */ __('Follow Us') ?></h4>

<?php if($block->getPosition() == 'footer'): ?>

<?php endif; ?>

<ul class="social-links position-<?php echo $block->getPosition() ?> type-<?php echo $block->getType() ?>">
    <?php foreach ($block->getAvailableSocialLinks() as $link): ?>
        <li>
            <?php echo $block->getRenderer()->setData($link)->toHtml(); ?>
        </li>
    <?php endforeach; ?>
</ul>
