<?php /**
 * @category    Ajh
 * @package     Ajh_Fitment
 * @copyright   Copyright (c) 2018-2019
 */ ?>

<?php
$fitment_years = $block->getFitmentYears();

$overview = $block->getFitmentOverview();

die;

$filters = $block->getFitmentParams();

$categories = $block->getCategories();

$skus = $block->getSkusInCategories();

$filterData = $block->getFitmentMetrics();
$garage = $block->getGarageVehicle();

$fitmentData = $block->getFitmentData();
?>
<div class="container">
    <div class="row mb-2">
        <div class="fitment_wrapper col-12 col-sm-9">
            <div class="d-flex flex-row bd-highlight">
                <div class="select-fitment-label"><h3>Select Your Vehicle</h3></div>
                <div class="fitment-main-wrap">
                    <div class="yemamosu-wrap">
                        <span class="year-wrapper">
                            <select name="year" id="fitment_year">
                                <option>Year</option>
                                <?php foreach ($fitment_years as $year): ?>
                                    <option value="<?php echo $year->getYear(); ?>"><?php echo $year->getYear(); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </span>                        
                        <span class="make-wrapper">
                            <select name="make" id="fitment_make" disabled="disabled">
                                <option>Make</option>
                                <option>-</option>
                            </select>
                        </span>
                        <span class="model-wrapper">
                            <select name="model" id="fitment_model" disabled="disabled">
                                <option>Model</option>
                                <option>-</option>
                            </select>
                        </span>
                        <span class="submodel-wrapper">
                            <select name="submodel" id="fitment_submodel" disabled="disabled">
                                <option>SubModel</option>
                                <option>-</option>
                            </select>
                        </span>
                    </div>
                    <div id="qualifier_wrap"></div>
                    <div class="fitment-action">
                        <button type="button" class="button btn-success" id="fitment_parts">Search</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="your-garage col-12 col-sm-3">                
            <select id="your-garage-select" onchange="loadFitmentCategories(this)">
                <option value="">Your Garage (<?php echo isset($garage['count']) ? $garage['count'] : 0; ?>)</option>
                <?php if (count($garage)): ?>        
                    <?php foreach ($garage as $key => $_vehicle): ?> 
                        <?php
                        $params = isset($_vehicle["params"]) ? $_vehicle["params"] : "";
                        $current_vehicle_id = isset($garage['current']) ? trim($garage['current']) : "";
                        $vehicle_id = isset($_vehicle['id']) ? trim($_vehicle['id']) : "";
                        $vehicle_name = isset($_vehicle['name']) ? $_vehicle['name'] : "";
                        ?>   
                        <?php if ($vehicle_id): ?>
                            <option value="<?php echo $params; ?>" <?php echo $vehicle_id === $current_vehicle_id ? 'selected="selected"' : ""; ?>>
                                <?php echo $vehicle_name; ?>
                            </option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>                   
        </div>        
    </div>
</div>
<?php if ($overview): ?>
    <div class="fitment-summary" style="clear: both;">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-8">        
                    <h2><?php echo $overview['year'] . "&nbsp;" . $overview['make']['Name'] . "&nbsp;" . $overview['model']['Name'] . "&nbsp;" . $overview['submodel']['Name']; ?></h2>
                    <div class="prodTxtBlock">
                        <h3>We have <strong><?php echo count($skus); ?> <?php echo count($skus) > 1 ? __('products') : __('product'); ?></strong> that fit the <strong><?php echo $overview['year'] . "&nbsp;" . $overview['make']['Name'] . "&nbsp;" . $overview['model']['Name'] . "&nbsp;" . $overview['submodel']['Name']; ?></strong><?php echo count($skus) ? __(', in these categories') : ""; ?>.</h3> 
                        <ul>
                            <?php foreach ($categories as $category): ?>                    
                                <?php if (strtolower($category['label']) !== 'label2'): //see category attribute under Category Menu tab ?>
                                    <li><a href="<?php echo $this->getBaseUrl() . 'fitment/index/products/?cat=' . $category['id'] . '&' . $filters['params']; ?>"><?php echo $category['name']; ?>  <span>(<?php echo count($category['products']); ?>)</span></a></li>
                                <?php endif; ?>
                            <?php endforeach; ?>        
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-sm-4">
                    <h2 class="text-right">About This Vehicle</h2>
                    <div class="text-right">
                        <?php
                        if (!empty($filterData)) {
                            foreach ($filterData as $key => $data) {
                                if (isset($fitmentData[$key])) {
                                    echo '<p>' . $fitmentData[$key] . ' : ' . $data . '</p>';
                                }
                            }
                        } else {
                            echo 'No Vehicle Found';
                        }
                        ?>
                    </div>

                    <?php /* $oeSensors = $block->getOeSensors();
                      ?>
                      <h2>OE Sensors</h2>
                      <?php $height = $oeSensors && $oeSensors->getSize() > 1 ? 160 : 'auto'; ?>
                      <div class="rightTxt oe-sensors-container">
                      <?php if ($oeSensors && $oeSensors->getSize() > 0) : ?>
                      <?php foreach ($oeSensors as $oeSensor): ?>
                      <div class="oe-img">
                      <?php if ($imageUrl = $block->getImageUrl($oeSensor->getData('ImageThumb'))): ?>
                      <img src="<?php echo $imageUrl; ?>" width="100px" />
                      <?php endif; ?>
                      </div>
                      <div class="oe-text">
                      <h3><strong>Part #</strong> <?php echo $oeSensor->getData('partnumber'); ?></h3>
                      </div>
                      <?php endforeach ?>
                      <?php else: ?>
                      <p><?php echo $block->getOeSensorsNoResultMsg() ?></p>
                      <?php endif ?>
                      </div> */ ?>


                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php
$ajaxurl = $block->getUrl('fitment/index/makes');
?>

<script type="text/x-magento-init">
    {
    "*": {
    "AJH_Fitment/js/fitmentajax": {
    "AjaxUrl": "<?php echo $ajaxurl; ?>",
    "StoreUrl": "<?php echo $block->getBaseUrl(); ?>"
    }
    }
    }
</script>
<script type="text/javascript">

    function loadFitmentCategories(ths) {
        if (ths.value !== "") {
            var location = "<?php echo $this->getUrl('fitment/index/categories') . "?" ?>" + ths.value;
            window.location = location;
        }
    }

    function setAjaxData(data, iframe) {
        if (data.status == 'ERROR') {
            // alert(data.message);
        } else {
            if (jQuery('.block-cart')) {
                jQuery('.block-cart').replaceWith(data.sidebar);
            }
            if (jQuery('.header .links')) {
                jQuery('.header .links').replaceWith(data.toplink);
            }
            jQuery.fancybox.close();
        }
    }
    function setLocationAjax(url, id) {
        url += 'isAjax/1';
        url = url.replace("checkout/cart", "ajaxcart/index");

        jQuery('#ajax_loader').show();
        try {
            jQuery.ajax({
                cache: false,
                url: url,
                dataType: 'json',
                success: function (data) {
                    jQuery('#ajax_loader').hide();
                    if (jQuery('.mini-cart')) {
                        jQuery('.mini-cart').replaceWith(data.sidebar);
                    }
                    if (jQuery('.header .links')) {
                        jQuery('.header .links').replaceWith(data.toplink);
                    }
                }
            });
        } catch (e) {
        }
    }
</script>