<?php
$fields = $block->getFields();
?>
<div class="set">
    <ul class="s">
        <li>
            <label for="business_type" class="">Business Type</label>
            <div class="">
                <select id="business_type" name="app[business_type]">
                    <option value="">--Select Business Type--</option>
                    <option value="Distributor/Salesman">Distributor / Salesman</option>
                    <option value="Fleet">Fleet</option>
                    <option value="General Auto Repair">General Auto Repair</option>
                    <option value="Retail Tire Chain">Retail Tire Chain (&gt; 2 locations)</option>
                    <option value="Retail Tire Store">Retail Tire Store</option>
                    <option value="Stereo Shop">Stereo Shop</option>
                    <option value="Tire Distributor (Wholesale)">Tire Distributor (Wholesale)</option>
                </select>
            </div>
        </li>
        <li>
            <label for="annual_sales" class="">Annual Sales</label>
            <div class="">
                <select id="annual_sales" name="app[annual_sales]">
                    <option value="">--Select Annual Sales Volume--</option>
                    <option value="1">1 - 999,999</option>
                    <option value="2">1,000,000 - 2,499,999</option>
                    <option value="3">2,500,000 - 4,999,999</option>
                    <option value="4">5,000,000 - 9,999,999</option>
                    <option value="5">&gt;10,000,000</option>
                </select>
            </div>
        </li>
        <li>
            <label for="employee_count" class="">Employee Count</label>
            <div class="">
                <select id="employee_count" name="app[employee_count]">
                    <option value="">--Select Number of Employees--</option>
                    <option value="1-3">1 - 3</option>
                    <option value="4-9">4 - 9</option>
                    <option value="10-24">10 - 24</option>
                    <option value="25-49">25 - 49</option>
                    <option value="50+">More than 50</option>
                </select>
            </div>
        </li>
        <li>
            <label for="heard_from" class="">How did you hear about our site?</label>
            <div class="">
                <select id="heard_from" name="app[heard_from]">
                    <option value="">--Make Selection--</option>
                    <option value="Friends">Friends</option>
                    <option value="Newspaper">Newspaper</option>
                    <option value="PDQ Distributor">Oro-Tek Distributor</option>
                    <option value="Other">Other</option>
                    <option value="Google">Google</option>
                    <option value="Yahoo">Yahoo</option>
                    <option value="Bing">Bing</option>
                    <option value="Facebook">Facebook</option>
                </select>
            </div>
        </li>
    </ul>
</div>

<div class="d2rRA-button-container">
    <button type="submit" class="d2rRA-submit d2rRA-button" onclick="retailerApplicationForm.sendApplication()"><?php echo __('Submit Application') ?></button>
</div>
