<?php ?>
<div class="wsap-success">
    <h1>Retailer Application</h1>

    <h2>Your application has been sent</h2>

    <p>Some thanks for newbies here</p>

    <p>We'll consider your retailer application in the sooner time and inform you on the result, whatever it will be.</p>

    <p>You'll be emailed.</p>

    <p><a href="<?php echo $block->getUrl() ?>"><?php echo __('Continue shopping') ?></a></p>

    <p>Thank you for your interest in doing business with <a href="www.PDQTPMS.com">www.PDQTPMS.com</a></p>

    <p><br>
        Sincerely,<br/>
        <br/>
        Darth Vader<br/>
        <br/>
        Retail Manager<br/>
        EMAIL: <a href="mailto:retail@pdqtpms.com">retail@pdqtpms.com</a>
    </p>

</div>