<?php
$postCollection = $block->getCollection();
$dateFormat = $this->getDateFormat();

if(!$postCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('There are no posts matching the selection.') ?></div>
    </div>
<?php else: ?>
<div class="posts-list-wrapper">
    <div class="toolbar-top">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
    <div class="posts-grid post-items">
        <?php foreach($postCollection as $post): ?>
            <div class="post-item" data-post-id="<?php echo $post->getPostId(); ?>">
                <div class="item-wrapper">

                    <!-- Image -->
                    <?php if ($image = $post->getImage()): ?>
                    <div class="post-image">
                        <a href="<?php echo $this->getPostUrl($post); ?>"><img src="<?php echo $image ?>" /></a>
                    </div>
                    <?php endif; ?>

                    <!-- Title -->
                    <h3 class="post-title">
                        <a href="<?php echo $this->getPostUrl($post); ?>"><?php echo $post->getTitle(); ?></a>
                    </h3>

                    <!-- Short Description -->
                    <div class="post-short-content">
                        <?php echo $block->filterContent($post->getShortContent()); ?>
                        <a href="<?php echo $this->getPostUrl($post); ?>" class="post-link">
                            <?php /* @escapeNotVerified */ echo __('more'); ?>...
                        </a>
                    </div>

                    <!-- Metadata -->
                    <div class="post-data">
                        <span class="create-date">
                            <time><?php echo date($dateFormat, strtotime($post->getCreationTime()));?></time>
                        </span>
                        <?php if ($author = $post->getAuthor()): ?>
                            <span class="post-author">
                                <span class="label"><?php echo __('by '); ?></span>
                                <span class="author"><?php echo $author; ?></span>
                            </span>
                        <?php endif; ?>
                        <?php if ($post->getCommentsEnabled()) : ?>
                            <span class="post-comments">
                                <a href="<?php echo $this->getPostUrl($post); ?>#post-comments">
                                    <?php echo $post->getApprovedComments()->count(); ?>
                                </a>
                            </span>
                        <?php endif; ?>
                    </div>

                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="toolbar-bottom">
        <?php echo $block->getChildHtml('blog_toolbar'); ?>
    </div>
</div>
<?php endif; ?>