<?php
/**
 * @var $block \AJH\Forms\Block\Index
 */
?>

<form action="<?php echo $block->getUrl("ajhforms/submit/index"); ?>" id="wheel-lock-registration" method="post">
    <div class="form-group field name required">
        <label for="firstname">First Name</label>
        <input type="text" class="form-control" id="firstname" name="firstname" value="" required="true" placeholder="First Name" />
    </div>
    <div class="form-group required">
        <label for="lastname">Last Name</label>
        <input type="text" class="form-control" id="lastname" name="lastname" value="" required="true" placeholder="Last Name" />
    </div>
    <div class="form-group required">
        <label for="email1address">Email Address</label>
        <input type="email" class="form-control" id="enailaddress" name="email" value="" required="true" placeholder="Enter email" />
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="keynumber">Key Number</label>
        <input type="text" class="form-control" id="keynumber" name="keynumber" placeholder="Key Number" required="true" />
    </div>
    <div class="form-group">
        <label for="">Type</label>        
        <div class="form-check type-field-radio">
            <input class="form-check-input" type="radio" name="type" id="type-lug-nut" value="Lug Nut" checked />
            <label class="form-check-label" for="type-lug-nut">Lug Nut</label>
        </div>
        <div class="form-check type-field-radio">
            <input class="form-check-input" type="radio" name="type" id="type-lug-bolt" value="Lug Bolt">
            <label class="form-check-label" for="type-lug-bolt">Lug Bolt</label>
        </div>
    </div>
    <div class="form-group">
        <label for="street-address">Street Address</label>
        <input type="text" class="form-control" id="street-address" name="address1" placeholder="Street Address" required="true" />
    </div>    
    <div class="form-group">
        <label for="address2">Address 2</label>
        <input type="text" class="form-control" id="address2" placeholder="Address 2" />
    </div>    
    <div class="form-group">
        <label for="region">State/Province/Region</label>
        <input type="text" class="form-control" id="region" name="state" placeholder="State/Province/Region" required="true" />
    </div>    
    <div class="form-group">
        <label for="postal">Postal/Zip Code</label>
        <input type="text" class="form-control" id="postal" name="zip" placeholder="Postal/Zip Code" required="true" />
    </div>    
    <div class="form-group">
        <label for="country">Country</label>
        <input type="text" class="form-control" id="country" name="country" placeholder="Country" required="true" />
    </div>    
    <div class="form-group">    
        <label for="phone">Phone</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone" required="true" />
    </div>    
    <hr/>
    <div class="form-group">    
        <button type="submit" class="btn btn-danger btn-lg">Submit</button>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#wheel-lock-registration": {
            "validation": {}
        }
    }
</script>